/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Knob: typeof import('primevue/knob')['default']
    Menubar: typeof import('./src/components/Menubar.vue')['default']
    ProjectDialog: typeof import('./src/components/ProjectDialog.vue')['default']
    ProjectHighlight: typeof import('./src/components/ProjectHighlight.vue')['default']
    ProjectsCarousel: typeof import('./src/components/ProjectsCarousel.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
